name: Publish To Github
on:
  workflow_call:
    inputs:
      RELEASE_TAG:
        type: string
        required: true

jobs:
  gh-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: temp
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.RELEASE_TAG }}
          name: ${{ inputs.RELEASE_TAG }}
          files: temp/libs/*.jar
          generate_release_notes: true
          fail_on_unmatched_files: true
